routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware( 'auth')->group(function () {
    Route::resource('/users', App\Http\Controllers\UsersController::class)->only('index', 'show');
    Route::resource('/photos', App\Http\Controllers\PhotosController::class)->only('store', 'destroy');

    Route::post('/subscribe/{user}', 'App\Http\Controllers\UsersController@subscribe')->name('subscribe');
    Route::post('/unsubscribe/{user}', 'App\Http\Controllers\UsersController@unsubscribe')->name('unsubscribe');

    Route::post('/like/{photo}', [App\Http\Controllers\PhotosController::class, 'like'])->name('like.photo');

    Route::resource('photos.comments', \App\Http\Controllers\CommentsController::class)->only(['store', 'update', 'destroy']);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Orchid\Filters\Types\Like;
use Orchid\Filters\Types\Where;
use Orchid\Filters\Types\WhereDateStartEnd;
use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
           'id'         => Where::class,
           'name'       => Like::class,
           'email'      => Like::class,
           'updated_at' => WhereDateStartEnd::class,
           'created_at' => WhereDateStartEnd::class,
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'updated_at',
        'created_at',
    ];

    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }


    /**
     * @return HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    /**
     * @return BelongsToMany
     */
    public function followers()
    {
        return $this->belongsToMany(User::class, 'followers', 'followed_id', 'follower_id');
    }


    /**
     * @return BelongsToMany
     */
    public function following()
    {
        return $this->belongsToMany(User::class, 'followers', 'follower_id', 'followed_id');
    }


    /**
     * @param User $user
     * @return bool
     */
    public function isFollowing(User $user)
    {
        return $this->following()->where('followed_id', $user->id)->exists();
    }


}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }



    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * @param Request $request
     * @param User $user
     * @return JsonResponse
     */
    public function subscribe(Request $request, User $user)
    {
        auth()->user()->following()->attach($user->id);

        return response()->json(['message' => 'Подписка успешно добавлена']);
    }

    /**
     * @param Request $request
     * @param User $user
     * @return JsonResponse
     */
    public function unsubscribe(Request $request, User $user): JsonResponse
    {
        auth()->user()->following()->detach($user->id);

        return response()->json(['message' => 'Подписка успешно удалена']);
    }


}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <div class="container">
        <div class="row">
            @foreach($users as $user)
                @if($user->id !== auth()->user()->id)
                    <div class="insta_card">
                        <div class="inf_user">
                            <div class="user_name"><img src="https://cdn-icons-png.flaticon.com/512/6596/6596121.png"
                                                        class="avatar" alt="">{{$user->name}}</div>
                            @if(auth()->user()->isFollowing($user))
                                <button data-user-id="{{ $user->id }}" class="unsubscribe">отписаться</button>
                            @else
                                <button data-user-id="{{ $user->id }}" class="subscribe">подписаться</button>
                            @endif
                        </div>


                        @foreach($user->photos as $photo)

                            <div class="photo_user">
                                <img src="{{ asset('/storage/' . $photo->photo)}}" class="d-block w-100" alt="...">
                            </div>
                            <div class="actions">
                                @if($photo->likedByUser(auth()->user()))
                                    <button class="like-button" data-photo-id="{{ $photo->id }}">
                                        <img src="{{asset('img/free-icon-heart-2589175.png')}}" alt=""
                                             style="width: 35px">
                                    </button>
                                @else
                                    <button class="like-button" data-photo-id="{{ $photo->id }}">
                                        <img src="{{asset('img/free-icon-heart-shape-outline-25424.png')}}" alt=""
                                             style="width: 35px">
                                    </button>
                                @endif
                                <span class="like-count"
                                      data-photo-id="{{ $photo->id }}">{{  $photo->likes()->count() }}</span>
                            </div>
                            <p class="d-inline-flex gap-1">
                                <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseExample{{$photo->id}}"
                                        aria-expanded="false" aria-controls="collapseExample{{$photo->id}}">
                                    Show all comments
                                </button>
                            </p>

                            <div class="collapse" id="collapseExample{{$photo->id}}">
                                <div class="card card-body" id="card-body">
                                    @foreach($photo->comments as $comment)
                                        @csrf
                                        <div class="card w-75 mb-3" id="delete-card-{{$comment->id}}">
                                            <input value="{{$comment->id}}" type="hidden" class="form-control"
                                                   id="comment_id"
                                                   name="comment_id">
{{--                                            @if($photo_id === $comment->$photo_id)                                                  // проблема--}}
                                            <div class="card-body">
                                                <h5 class="card-title"><b>Author:</b>{{ $comment->user->name}}</h5>
                                                <p class="card-text comment-text">
                                                    <b>Comment:</b> {{ $comment->comment }}</p>
                                                <textarea class="form-control comment-input mt-2" id="comment"
                                                          name="comment"
                                                          style="display: none;">{{ $comment->comment }}</textarea>
                                                @can('delete', $comment)
                                                    <button class="btn btn-primary delete-comment-btn mt-2"
                                                            data-id="{{$comment->id}}">delete
                                                    </button>
                                                @endcan
                                                @can('update', $comment)
                                                    <button class="btn btn-primary update-comment-btn mt-2"
                                                            type="button"
                                                            data-value="{{$comment->id}}">
                                                        update
                                                    </button>
                                                @endcan
                                            </div>
{{--                                            @endif                                                                                  //конец проблемы--}}
                                        </div>
                                    @endforeach
                                </div>

                                @if($photo->user_id !== Auth::user()->id)
                                <div id="comment-form">
                                    <form id="create-comment">
                                        @csrf
                                        <input type="hidden" id="photo_id" value="{{$photo->id}}">
                                        <div class="form-group mt-2">
                                            <label for="comment">Comment</label>
                                            <textarea class="form-control" id="comment" name="comment"></textarea>
                                            @error('comment')
                                            <div class="alert alert-danger">{{$message}}</div>
                                            @enderror
                                        </div>
                                        <div class="text-center">
                                            <button id="create-comment-btn" type="submit"
                                                    class="mt-3 btn btn-outline-primary btn-sm btn-block">
                                                Add new comment
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                    @endif
                            </div>
                            <div style="height: 40px"></div>
                        @endforeach
                        {{--                    @endif--}}
                    </div>
                @endif
            @endforeach
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container body">
        <div class="row">
            <div class="col bg-over">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="d-flex" style="justify-content: space-between;">
                            <h5 class="card-title"><b>{{ $user->name}}</b></h5>
                            <div style="display: flex; gap: 10px">
                                <p><b>подписчики</b> {{ $user->followers()->count() }}</p>
                                <p><b>подписки</b> {{ $user->following()->count() }}</p>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col">

                        <div style="width: 90%">
                            <p class="d-inline-flex gap-1">
                                <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseExample" aria-expanded="false"
                                        aria-controls="collapseExample">
                                    add photo
                                </button>
                            </p>
                            <div class="collapse" id="collapseExample">
                                <form method="post" action="{{ route('photos.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" name="user_id" id="user_id" value="{{$user->id}}">
                                    <div class="form-group">
                                        <label for="photo" class="form-label">Choose file</label>
                                        <input value="{{old('photo')}}" class="form-control" type="file" id="photo"
                                               name="photo">
                                        @error('photo')
                                        <div class="alert alert-danger">{{$message}}</div>
                                        @enderror
                                    </div>
                                    <div class="mt-2">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="uni-box">
                    @foreach($user->photos as $photo)
                        <div style="border: 1px solid #b1aaaa;">
                            <div class="card" style="width: 18rem; margin-bottom: 20px;">
                                <div class="img-box">
                                    <img src="{{ asset('/storage/' . $photo->photo)}}" alt="{{$photo->photo}}">
                                </div>

                                <div class="actions">
                                    @if($photo->likedByUser(auth()->user()))
                                        <button class="like-button" data-photo-id="{{ $photo->id }}">
                                            <img src="{{asset('img/free-icon-heart-2589175.png')}}" alt=""
                                                 style="width: 35px">
                                        </button>
                                    @else
                                        <button class="like-button" data-photo-id="{{ $photo->id }}">
                                            <img src="{{asset('img/free-icon-heart-shape-outline-25424.png')}}" alt=""
                                                 style="width: 35px">
                                        </button>
                                    @endif
                                    <span class="like-count"
                                          data-photo-id="{{ $photo->id }}">{{  $photo->likes()->count() }}</span>
                                </div>
                            </div>
                            <div style="width: 90%;    margin: auto;" class="pb-3">
                                <p class="d-inline-flex gap-1">
                                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#collapseExample{{$photo->id}}"
                                            aria-expanded="false" aria-controls="collapseExample{{$photo->id}}">
                                        Show all comments
                                    </button>
                                    `
                                </p>

                                <div class="collapse" id="collapseExample{{$photo->id}}">
                                    <div class="card card-body" id="card-body">
                                        @foreach($photo->comments as $comment)
                                            @csrf
                                            <div class="card w-75 mb-3" id="delete-card-{{$comment->id}}">
                                                <input value="{{$comment->id}}" type="hidden" class="form-control"
                                                       id="comment_id"
                                                       name="comment_id">
                                                @dd($photo_id)
                                                @if($photo_id === $comment->$photo_id)
                                                    <div class="card-body">
                                                        <h5 class="card-title"><b>Author:</b>{{ $comment->user->name}}
                                                        </h5>
                                                        <p class="card-text comment-text">
                                                            <b>Comment:</b> {{ $comment->comment }}</p>
                                                        <textarea class="form-control comment-input mt-2" id="comment"
                                                                  name="comment"
                                                                  style="display: none;">{{ $comment->comment }}</textarea>
                                                        @can('delete', $comment)
                                                            <button class="btn btn-primary delete-comment-btn mt-2"
                                                                    data-id="{{$comment->id}}">delete
                                                            </button>
                                                        @endcan
                                                        @can('update', $comment)
                                                            <button class="btn btn-primary update-comment-btn mt-2"
                                                                    type="button"
                                                                    data-value="{{$comment->id}}">
                                                                update
                                                            </button>
                                                        @endcan
                                                    </div>
                                                @endif
                                            </div>
                                        @endforeach
                                    </div>
                                    @if($photo->user_id !== Auth::user()->id)
                                        <div id="comment-form">
                                            <form id="create-comment">
                                                @csrf
                                                <input type="hidden" id="photo_id" value="{{$photo->id}}">
                                                <div class="form-group mt-2">
                                                    <label for="comment">Comment</label>
                                                    <textarea class="form-control" id="comment"
                                                              name="comment"></textarea>
                                                    @error('comment')
                                                    <div class="alert alert-danger">{{$message}}</div>
                                                    @enderror
                                                </div>
                                                <div class="text-center">
                                                    <button id="create-comment-btn" type="submit"
                                                            class="mt-3 btn btn-outline-primary btn-sm btn-block">
                                                        Add new comment
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    @endif
                                </div>

                                <div class="">
                                    <form class="" method="post"
                                          action="{{ route('photos.destroy', ['photo' => $photo]) }}">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">Remove</button>
                                    </form>
                                </div>
                            </div>


                        </div>

                    @endforeach
                </div>

            </div>

        </div>
    </div>
    </div>



@endsection