routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware( 'auth')->group(function () {
    Route::resource('/users', App\Http\Controllers\UsersController::class)->only('index', 'show');
    Route::resource('/photos', App\Http\Controllers\PhotosController::class)->only('store', 'destroy');

    Route::post('/subscribe/{user}', 'App\Http\Controllers\UsersController@subscribe')->name('subscribe');
    Route::post('/unsubscribe/{user}', 'App\Http\Controllers\UsersController@unsubscribe')->name('unsubscribe');

    Route::post('/like/{photo}', [App\Http\Controllers\PhotosController::class, 'like'])->name('like.photo');

    Route::resource('photos.comments', \App\Http\Controllers\CommentsController::class)->only(['store', 'update', 'destroy']);

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link href="../../../css/app.css" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<style>
    .navbar-brand img {
        max-width: 150px;
        height: auto;
        vertical-align: middle;
        margin-right: 10px;
    }
</style>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/users') }}">
                <img id="centered-image" src="{{asset('img/logo-instagram-new.jpg')}}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="user-head" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav me-auto">

                </ul>


                @if(Auth::check())

                    <li class="nav-item" style="padding: 8px">
                        <a href="{{route('users.show', ['user' => Auth::user()])}}">
                            <img style="width: 33px; height: 33px"
                                 src="{{asset('img/free-icon-user-profile-3985429.png')}}" alt="">
                        </a>
                    </li>

                    @if(Auth::user()->permissions['platform.systems.users'])
                        <li class="nav-item" style="padding: 8px">
                            <a href="{{route('platform.main')}}" class="btn btn-secondary">
                                ORCHID
                            </a>
                        </li>
                @endif
            @endif

            <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

</body>
</html>